### ISSUE TITLE
The postgres DB provisioned in box 'db' doesn't seem to know about `jsonb`

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/vagrant-opencivicdata.org#11]
Not completely sure this is the right place for this.

```
 pupa dbinit us
no pupa_settings on path, using defaults
Operations to perform:
  Apply all migrations: pupa, opencivicdata
Running migrations:
  Rendering model states... DONE
  Applying opencivicdata.0001_initial...Traceback (most recent call last):
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: type "jsonb" does not exist
LINE 1: ...d_at" timestamp with time zone NOT NULL, "extras" jsonb NOT ...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fgregg/public/opencivicdata/.env/bin/pupa", line 9, in <module>
    load_entry_point('pupa==0.5.0', 'console_scripts', 'pupa')()
  File "/home/fgregg/public/opencivicdata/.env/src/pupa/pupa/cli/__main__.py", line 71, in main
    subcommands[args.subcommand].handle(args, other)
  File "/home/fgregg/public/opencivicdata/.env/src/pupa/pupa/cli/commands/dbinit.py", line 53, in handle
    call_command('migrate', interactive=False)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/contrib/gis/db/backends/postgis/schema.py", line 56, in create_model
    super(PostGISSchemaEditor, self).create_model(model)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/backends/base/schema.py", line 284, in create_model
    self.execute(sql, params or None)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: type "jsonb" does not exist
LINE 1: ...d_at" timestamp with time zone NOT NULL, "extras" jsonb NOT ...
```                                                             ^

**Comment by fgregg** [comment]
On the vagrant box, here's the version;

``` PostgreSQL 9.3.10 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit
```

**Comment by murdav** [comment]
As a result, the usage of this field is only supported on PostgreSQL versions at least 9.4.

From https://docs.djangoproject.com/en/dev/ref/contrib/postgres/fields/#django.contrib.postgres.fields.JSONField
